name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore & Build Backend
        run: |
          cd ./BookNest.API
          dotnet restore
          dotnet build --configuration Release

      - name: Start backend API
        run: |
          cd ./BookNest.API
          nohup dotnet run --urls "http://localhost:5000" &
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Angular
        run: |
          cd ./BookNest.UI
          npm install
          npm run build

      - name: Run Playwright Tests
        run: |
          cd ./BookNest.UI
          npx playwright install --with-deps
          npx playwright test --reporter=html
